AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Senzing aws-cloudformation-ecs-spike-list-hosted-zones Version: 0.1.0
  For more information see https://github.com/senzing-garage/aws-cloudformation-ecs

Parameters:
  Route53HostedZoneId:
    Description: 'Help: https://hub.senzing.com/aws-cloudformation-ecs/senzing-demo-hosted-zone/#route53hostedzoneid'
    Type: AWS::Route53::HostedZone::Id


Conditions:
  IfRoute53HostedZoneId: !Not
    - !Equals
      - !Ref Route53HostedZoneId
      - ''

Resources:
  Ec2Vpc:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2-vpc"
    Type: AWS::EC2::VPC


Outputs:
  Route53HostedZoneId:
    Description: 'Route53HostedZoneId'
    Value: !If
      - IfRoute53HostedZoneId
      - !Ref Route53HostedZoneId
      - !Sub "{AWS::NoValue}"
